apiVersion: v1
kind: Secret
metadata:
  name: serphawk-backend-secret
  namespace: serphawk
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3NlcnBoYXdrOnZGY35tJTNGRiUzRWMlNUIyRW00WmR6WnVLenR5cGMhMXZAc2VycGhhd2stcG9zdGdyZXMuY3htdXdjY3lrdWd6LmFwLXNvdXRoLTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9zZXJwaGF3aw==
